services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - PORT=8000
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-secret-key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DATABASE_URL=${DATABASE_URL:-}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - CORS_ALLOW_ALL=${CORS_ALLOW_ALL:-True}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:-us-east-2}
    restart: always
    mem_limit: 450m
    memswap_limit: 450m
