# Generated by Django 4.2.7 on 2026-03-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Análisis y Desarrollo de Software', max_length=200, unique=True, verbose_name='Nombre del programa')),
                ('codigo', models.CharField(help_text='Ej: 228106', max_length=50, unique=True, verbose_name='Código del programa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del programa (opcional)', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo para que no aparezca en el registro de nuevos aprendices', verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Programa de Formación',
                'verbose_name_plural': 'Programas de Formación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de la ficha. Ej: 2898734', max_length=20, unique=True, verbose_name='Número de ficha')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin proyectada')),
                ('activa', models.BooleanField(default=True, help_text='Desactívala cuando el grupo se gradúe', verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='formacion.programa', verbose_name='Programa de formación')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
