# Generated by Django 4.2.7 on 2025-09-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_reunion', models.CharField(choices=[('consejo_academico', 'Consejo Académico'), ('comite_evaluacion', 'Comité de Evaluación'), ('coordinacion', 'Coordinación'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=30)),
                ('fecha_reunion', models.DateTimeField()),
                ('lugar_reunion', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('finalizada', 'Finalizada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('orden_dia', models.TextField(help_text='Orden del día de la reunión')),
                ('desarrollo', models.TextField(help_text='Desarrollo de la reunión')),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen generado por IA')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_limite_firmas', models.DateTimeField(blank=True, null=True)),
                ('silencio_administrativo', models.BooleanField(default=False)),
                ('aplicar_silencio_dias', models.IntegerField(default=7)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actas/adjuntos/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_finalize_acta', 'Puede finalizar actas'), ('can_archive_acta', 'Puede archivar actas')],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='actas.acta')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_reunion', models.CharField(blank=True, max_length=100)),
                ('obligatorio_firma', models.BooleanField(default=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='actas.acta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('acta', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas_actas/')),
                ('firmado_por_silencio', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='actas.acta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
                'unique_together': {('acta', 'usuario')},
            },
        ),
    ]
