# Generated by Django 4.2.7 on 2025-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_comentarioacta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='reporte_cumplimiento',
            field=models.TextField(blank=True, help_text='Descripción del avance o justificación del estado/cumplimiento.', verbose_name='Reporte/Justificación del Responsable'),
        ),
    ]
