# Generated by Django 4.2.7 on 2025-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_compromiso_reporte_cumplimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='firma_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
