# Generated by Django 4.2.7 on 2025-11-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_alter_firma_firma_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_finalize_acta', 'Puede finalizar actas'), ('can_archive_acta', 'Puede archivar actas'), ('can_generate_with_ia', 'Puede generar actas con IA')], 'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
        migrations.AddField(
            model_name='acta',
            name='editada_despues_ia',
            field=models.BooleanField(default=False, help_text='Indica si el acta fue modificada manualmente después de ser generada por IA'),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_ultima_edicion_manual',
            field=models.DateTimeField(blank=True, help_text='Última vez que se editó manualmente después de generar con IA', null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='generada_con_ia',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el acta fue generada usando Ollama'),
        ),
        migrations.AddField(
            model_name='acta',
            name='modelo_ia_usado',
            field=models.CharField(blank=True, help_text='Ejemplo: llama3:8b, llama3:70b, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='prompt_original',
            field=models.TextField(blank=True, help_text='Resumen breve que el usuario proporcionó para generar el acta', null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='tiempo_generacion',
            field=models.FloatField(blank=True, help_text='Tiempo en segundos que tomó Ollama en generar el acta', null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='version',
            field=models.IntegerField(default=1, help_text='Número de versión del acta (incrementa con cada edición)'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['fecha_creacion'], name='actas_acta_fecha_c_edd56d_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['estado'], name='actas_acta_estado_502f90_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['fecha_reunion'], name='actas_acta_fecha_r_fbb9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['generada_con_ia'], name='actas_acta_generad_872326_idx'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['creador', 'fecha_creacion'], name='actas_acta_creador_a3fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioacta',
            index=models.Index(fields=['acta', 'fecha'], name='actas_comen_acta_id_3259e4_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['fecha_limite', 'estado'], name='actas_compr_fecha_l_544cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['responsable', 'estado'], name='actas_compr_respons_8cf0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['acta'], name='actas_compr_acta_id_900a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='firma',
            index=models.Index(fields=['acta', 'firmado'], name='actas_firma_acta_id_6d1d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='firma',
            index=models.Index(fields=['usuario', 'firmado'], name='actas_firma_usuario_d8f113_idx'),
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['acta', 'usuario'], name='actas_parti_acta_id_fb930b_idx'),
        ),
    ]
