# Generated by Django 4.2.7 on 2026-01-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actas', '0005_alter_acta_options_acta_editada_despues_ia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo adjunto', upload_to='actas/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('tipo_archivo', models.CharField(help_text='Extensión: pdf, docx, xlsx, jpg, png, zip, etc.', max_length=100)),
                ('tamaño_bytes', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del archivo')),
                ('acta', models.ForeignKey(help_text='Acta a la que pertenece el archivo', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='actas.acta')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['acta', 'fecha_subida'], name='actas_archi_acta_id_e4a645_idx')],
            },
        ),
    ]
