# Generated by Django 4.2.7 on 2026-03-03 16:48

import actas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0007_alter_acta_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='actas/adjuntos/', validators=[actas.models.validar_extension_archivo, actas.models.validar_contenido_archivo, actas.models.validar_tamaño_archivo]),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(help_text='Archivo adjunto', upload_to='actas/adjuntos/%Y/%m/', validators=[actas.models.validar_extension_archivo, actas.models.validar_contenido_archivo, actas.models.validar_tamaño_archivo]),
        ),
    ]
