# Generated by Django 4.2.7 on 2026-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0011_acta_tipo_acta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anexoacta',
            new_name='actas_anexo_acta_id_73c0de_idx',
            old_name='actas_anexo_acta_id_orden_idx',
        ),
        migrations.RenameIndex(
            model_name='participante',
            new_name='actas_parti_acta_id_530925_idx',
            old_name='actas_parti_acta_id_estado_idx',
        ),
        migrations.AddField(
            model_name='firma',
            name='firma_datos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del participante (motivo del rechazo o comentarios de aprobación)'),
        ),
    ]
