# Generated by Django 4.2.7 on 2026-03-25 22:14

import actas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actas', '0012_add_firma_datos_to_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reunion', models.CharField(choices=[('consejo_academico', 'Consejo Académico'), ('comite_evaluacion', 'Comité de Evaluación'), ('coordinacion', 'Coordinación'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], help_text='Solo puede haber una plantilla activa por tipo de reunión.', max_length=30, unique=True, verbose_name='Tipo de reunión')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar la plantilla (ej: "Formato Consejo v2").', max_length=200, verbose_name='Nombre de la plantilla')),
                ('archivo', models.FileField(help_text='Suba un archivo .docx con los {{marcadores}} en las posiciones deseadas.', upload_to='plantillas_actas/%Y/%m/', validators=[actas.models.validar_plantilla_docx], verbose_name='Archivo Word (.docx)')),
                ('activa', models.BooleanField(default=True, help_text='Solo las plantillas activas se usan para generar PDFs.', verbose_name='Activa')),
                ('descripcion', models.TextField(blank=True, help_text='Notas sobre esta plantilla (opcional).', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Plantilla de Acta',
                'verbose_name_plural': 'Plantillas de Acta',
                'ordering': ['tipo_reunion'],
            },
        ),
    ]
