# Generated by Django 4.2.7 on 2026-04-09 00:27

from django.db import migrations, models


def asignar_numeros_provisionales(apps, schema_editor):
    """
    Actas existentes con números automáticos cortos (ej: "ACT-2026-0001")
    se dejan como están ya que siguen siendo únicos y válidos.
    Solo nos aseguramos de que ninguna quede sin número.
    """
    Acta = apps.get_model('actas', 'Acta')
    for acta in Acta.objects.filter(numero_acta='').order_by('id'):
        year = acta.fecha_creacion.year if acta.fecha_creacion else 2026
        acta.numero_acta = f"ACT-{year}-{acta.id:03d}"
        acta.save(update_fields=['numero_acta'])


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0013_add_plantilla_acta_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='numero_acta',
            field=models.CharField(help_text='Número oficial asignado por la subdirección. Ej: ACT-2026-COORD-001', max_length=50, unique=True, verbose_name='Número de Acta'),
        ),
        migrations.RunPython(asignar_numeros_provisionales, migrations.RunPython.noop),
    ]
