# Generated by Django 4.2.7 on 2026-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0014_numero_acta_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='tipo_reunion_otro',
            field=models.CharField(blank=True, default='', help_text='Solo se usa cuando tipo_reunion="otra". Especifique el tipo exacto.', max_length=100, verbose_name='Tipo de reunión personalizado'),
        ),
    ]
