# Generated by Django 4.2.7 on 2026-04-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0015_add_tipo_reunion_otro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteNoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('cargo_rol', models.CharField(blank=True, default='', help_text='Ej: Aprendiz, Invitado externo, Contratista', max_length=100, verbose_name='Cargo / Rol')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pdf_enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('email_rebotado', models.BooleanField(default=False)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_no_registrados', to='actas.acta')),
            ],
            options={
                'verbose_name': 'Participante No Registrado',
                'verbose_name_plural': 'Participantes No Registrados',
                'ordering': ['nombre_completo'],
                'unique_together': {('acta', 'email')},
            },
        ),
    ]
