# Generated by Django 4.2.7 on 2026-04-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0016_participante_no_registrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_finalize_acta', 'Puede finalizar actas'), ('can_archive_acta', 'Puede archivar actas'), ('can_generate_with_ia', 'Puede generar actas con IA'), ('aprobar_acta', 'Puede aprobar actas'), ('rechazar_acta', 'Puede rechazar actas'), ('enviar_a_revision', 'Puede enviar actas a revisión'), ('generar_pdf_acta', 'Puede generar PDF de actas'), ('firmar_acta', 'Puede firmar actas')], 'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
    ]
