# Generated by Django 4.2.7 on 2026-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0017_add_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='centro',
            field=models.CharField(blank=True, default='Centro Minero', max_length=150, verbose_name='Centro'),
        ),
        migrations.AddField(
            model_name='acta',
            name='ciudad',
            field=models.CharField(blank=True, default='', help_text='Ej: Sogamoso, Boyacá', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='acta',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección física. Ej: Cra 9 #14-109', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='acta',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de finalización de la reunión (HH:MM)', null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='acta',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio de la reunión (HH:MM)', null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='acta',
            name='lugar_enlace',
            field=models.TextField(blank=True, default='', help_text='Dirección física o enlace virtual (Teams, Zoom, Google Meet)', verbose_name='Lugar y/o enlace'),
        ),
        migrations.AddField(
            model_name='acta',
            name='objetivos',
            field=models.TextField(blank=True, default='', help_text='Verbos en infinitivo. Ej: 1. Revisar... 2. Evaluar...', verbose_name='Objetivo(s) de la reunión'),
        ),
        migrations.AddField(
            model_name='acta',
            name='regional',
            field=models.CharField(blank=True, default='Boyacá', max_length=100, verbose_name='Regional'),
        ),
        migrations.AddField(
            model_name='participante',
            name='dependencia_empresa',
            field=models.CharField(blank=True, default='SENA - CENTRO MINERO', help_text='Ej: SENA - CENTRO MINERO, Alcaldía de Sogamoso', max_length=200, verbose_name='Dependencia / Empresa'),
        ),
        migrations.AddField(
            model_name='participantenoregistrado',
            name='dependencia_empresa',
            field=models.CharField(blank=True, default='', help_text='Ej: Alcaldía de Sogamoso, Empresa XYZ S.A.S.', max_length=200, verbose_name='Dependencia / Empresa'),
        ),
    ]
