# Generated by Django 4.2.7 on 2025-09-25 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_firma_pendiente', models.BooleanField(default=True)),
                ('email_compromiso_vencido', models.BooleanField(default=True)),
                ('email_nueva_acta', models.BooleanField(default=True)),
                ('app_todas_notificaciones', models.BooleanField(default=True)),
                ('resumen_email', models.CharField(choices=[('nunca', 'Nunca'), ('diario', 'Diario'), ('semanal', 'Semanal')], default='semanal', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuracion de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('firma_pendiente', 'Firma Pendiente'), ('firma_completada', 'Firma Completada'), ('acta_lista_finalizar', 'Acta Lista para Finalizar'), ('compromiso_vencido', 'Compromiso Vencido'), ('compromiso_proximo', 'Compromiso Próximo a Vencer'), ('silencio_administrativo', 'Silencio Administrativo'), ('nueva_acta', 'Nueva Acta '), ('acta_finalizada', 'Acta Finalizada'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('enlace', models.URLField(blank=True, help_text='URL para redireccionar al hacer clic')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8fe80f_idx'), models.Index(fields=['fecha_creacion'], name='notificatio_fecha_c_929fc4_idx'), models.Index(fields=['tipo'], name='notificatio_tipo_d22b91_idx')],
            },
        ),
    ]
