# Generated by Django 4.2.7 on 2025-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('firma_pendiente', 'Firma Pendiente'), ('firma_completada', 'Firma Completada'), ('acta_lista_finalizar', 'Acta Lista para Finalizar'), ('compromiso_vencido', 'Compromiso Vencido'), ('compromiso_proximo', 'Compromiso Próximo a Vencer'), ('silencio_administrativo', 'Silencio Administrativo'), ('nueva_acta', 'Nueva Acta '), ('acta_finalizada', 'Acta Finalizada'), ('sistema', 'Notificación del Sistema')], max_length=30),
        ),
    ]
