# Generated by Django 4.2.7 on 2025-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='enlace',
            field=models.URLField(blank=True, help_text='URL para redireccionar al hacer clic'),
        ),
    ]
