# Generated by Django 4.2.7 on 2026-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('firma_pendiente', 'Firma Pendiente'), ('firma_completada', 'Firma Completada'), ('acta_lista_finalizar', 'Acta Lista para Finalizar'), ('compromiso_vencido', 'Compromiso Vencido'), ('compromiso_proximo', 'Compromiso Próximo a Vencer'), ('silencio_administrativo', 'Silencio Administrativo'), ('nueva_acta', 'Nueva Acta '), ('acta_finalizada', 'Acta Finalizada'), ('sistema', 'Notificación del Sistema'), ('nueva_solicitud_rol', 'Nueva Solicitud de Rol'), ('revision_pendiente', 'Revisión Pendiente'), ('acta_aprobada_parcial', 'Participante Aprobó Acta'), ('acta_rechazada', 'Participante Rechazó Acta'), ('acta_cerrada', 'Acta Cerrada por Vencimiento')], max_length=30),
        ),
    ]
