# Generated by Django 4.2.7 on 2025-10-11 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('funcionario', 'Funcionario'), ('coordinador', 'Coordinador'), ('director', 'Director'), ('admin', 'Administrador'), ('instructor', 'Instructor'), ('aprendiz', 'Aprendiz')], default='funcionario', max_length=20),
        ),
    ]
