# Generated by Django 4.2.7 on 2025-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('funcionario', 'Funcionario'), ('coordinador', 'Coordinador'), ('director', 'Director'), ('admin', 'Administrador'), ('instructor', 'Instructor'), ('aprendiz', 'Aprendiz'), ('instructor', 'Instructor'), ('aprendiz', 'Aprendiz')], default='funcionario', max_length=20),
        ),
    ]
