# Generated by Django 4.2.7 on 2025-12-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuenta_aprobada',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta está aprobada para uso'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario verificó su email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('instructor', 'Instructor'), ('invitado', 'Invitado'), ('funcionario', 'Funcionario'), ('coordinador', 'Coordinador'), ('director', 'Director'), ('admin', 'Administrador')], default='invitado', max_length=20),
        ),
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 6 dígitos numéricos', max_length=6)),
                ('tipo', models.CharField(choices=[('registro', 'Registro'), ('recuperacion', 'Recuperación de contraseña')], default='registro', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
