# Generated by Django 4.2.7 on 2026-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cuenta_aprobada_user_email_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacion',
            name='codigo',
            field=models.CharField(help_text='Código de 8 dígitos numéricos', max_length=8),
        ),
    ]
