# Generated by Django 4.2.7 on 2026-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cambiar_codigo_a_8_digitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacion',
            name='codigo',
            field=models.CharField(help_text='Código de 6 dígitos numéricos', max_length=6),
        ),
    ]
