# Generated by Django 4.2.7 on 2026-02-19 14:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_revertir_codigo_a_6_digitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre de usuario.'}, max_length=150, unique=True, validators=[accounts.models.UsernameValidator()]),
        ),
    ]
