# Generated by Django 4.2.7 on 2026-03-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número único de identificación (CC, TI, CE, etc.). Es el identificador de login.', max_length=50, null=True, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('OTRO', 'Otro')], default='', max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
