# Generated by Django 4.2.7 on 2026-03-04 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
        ('accounts', '0011_asignar_documentos_temporales'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ficha',
            field=models.ForeignKey(blank=True, help_text='Solo para aprendices. Ficha (grupo) a la que pertenece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='formacion.ficha', verbose_name='Ficha de formación'),
        ),
    ]
