# Generated by Django 4.2.7 on 2026-03-16 13:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_estado_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Se rellena automáticamente cuando el admin aprueba la cuenta', null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', validators=[accounts.models.validar_firma_digital]),
        ),
        migrations.AlterField(
            model_name='user',
            name='observaciones_aprobacion',
            field=models.TextField(blank=True, default='', help_text='Notas del administrador sobre la aprobación o rechazo', verbose_name='Observaciones de aprobación'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rol'], name='accounts_user_rol_idx'),
        ),
    ]
