"""
Django settings for sistema_actas project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os  # Modulo para interpretar el sistema operativo
from decouple import config  # Permite manejar variables de entorno desde .env
from pathlib import Path  # Para manejanvr rutas del sistema de forma segura
from dotenv import load_dotenv  # Cargar variables de entorno desde .env
import dj_database_url  # Para parsear DATABASE_URL de Railway/Heroku

load_dotenv()

# OPENAI_API_KEY ya no se usa - el proyecto usa GROQ
# La configuración de GROQ está en las líneas 302-309
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", default="")  # Opcional, legacy

# Directorio de logs (solo para desarrollo local)
LOGS_DIR = os.path.join("logs")
try:
    os.makedirs(LOGS_DIR, exist_ok=True)
except Exception:
    LOGS_DIR = "/tmp/logs"
    os.makedirs(LOGS_DIR, exist_ok=True)


# Base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.com/en/5.2/howto/deployment/checklist/

# Clave secreta para seguridad de Django(lee desde .env)
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me-in-production")
# Modo de depuarcion, True en desarrollo,False en produccion
DEBUG = config("DEBUG", default=True, cast=bool)
# Lista de hosts permitidos para acceder al proyecto
# En producción, especificar dominios exactos separados por coma en .env
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# En modo DEBUG, agregar dominios de ngrok automáticamente
if DEBUG:
    ALLOWED_HOSTS += [
        '.ngrok.io',
        '.ngrok-free.app',
        '.ngrok.app',
        '.ngrok-free.dev',
        '.localhost',
        '127.0.0.1',
    ]

# Railway y otros servicios de hosting
ALLOWED_HOSTS += [
    '.railway.app',
    '.up.railway.app',
]

# AWS Elastic Beanstalk
ALLOWED_HOSTS += [
    '.elasticbeanstalk.com',
    '.us-east-2.elasticbeanstalk.com',
    'sistema-actas-env.eba-yjpjmjq2.us-east-2.elasticbeanstalk.com',  # Dominio explícito
]

# Si hay RAILWAY_STATIC_URL, estamos en Railway
if os.environ.get('RAILWAY_STATIC_URL'):
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_STATIC_URL', '').replace('https://', '').replace('http://', '').split('/')[0])


# Application definition

INSTALLED_APPS = [
    # Apps de Django por defecto
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django_extensions",
    # Aplicaciones de terceros(Externas)
    "crispy_forms",  # Formularios más amigables
    "crispy_bootstrap5",  # Integración de Crispy con Bootstrap 5
    "ckeditor",  # Editor de texto enriquecido
    "ckeditor_uploader",  # Subida de archivos en CKEditor
    "rest_framework",  # API con Django REST Framework
    "rest_framework.authtoken",  # Sistema de tokens para autenticación API
    "corsheaders",  # Manejo de CORS
    "import_export",  # Importación/exportación de datos en admin
    # Apps Propias
    "accounts",  # Gestión de usuarios
    "actas",  # Módulo principal de actas
    "core",  # Funcionalidades compartidas (ej. context processors)
    "notifications",  # Sistema de notificaciones
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Manejo de CORS (API)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Servir archivos estáticos en producción
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # Protección contra CSRF
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Protección contra Clickjacking
    "sistema_actas.security.SecurityMiddleware",  # Seguridad personalizada (XSS, SQLi detection)
    "sistema_actas.security.AuditLogMiddleware",  # Auditoría de acciones
]

ROOT_URLCONF = "sistema_actas.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Carpeta global de templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.notifications_count",  # Context processor personalizado
            ],
        },
    },
]

WSGI_APPLICATION = "sistema_actas.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración por defecto (desarrollo local con SQLite)
DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_NAME", default=BASE_DIR / "db.sqlite3"),
        "USER": config("DB_USER", default=""),
        "PASSWORD": config("DB_PASSWORD", default=""),
        "HOST": config("DB_HOST", default=""),
        "PORT": config("DB_PORT", default=""),
    }
}

# Si existe DATABASE_URL (Railway, Heroku, etc.), usarla
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-CO"  # Idioma Principal

TIME_ZONE = "America/Bogota"  # Zona horaria de colombia

USE_I18N = True  # Traduccion internacional

USE_TZ = True  # Manejo de zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Para produccion
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "core",  # 👈 importante, para que Django sirva también core/js/
]

MEDIA_URL = "/media/"  # Archivos subidos por usuarios
MEDIA_ROOT = BASE_DIR / "media"

# File upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000


# Default primary key field type
# https://docs.djangoproject.com/en5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Usuario Personalizado
AUTH_USER_MODEL = "accounts.User"

# Django crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# CKEditor (Editor de texto enriquecido)
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 400,
        "width": "100%",
    },
}

# Celery + Redis (tareas asincronas)
# En producción, configurar Redis con autenticación en .env
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://localhost:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Rate limiting
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = "default"

# Backup Settings
BACKUP_LOCAL_DIRECTORY = BASE_DIR / "backups"
BACKUP_KEEP_DAYS = 30

# Sesiones
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# CSRF Protection
CSRF_COOKIE_HTTPONLY = False  # Necesario para que JavaScript pueda leer el token
CSRF_COOKIE_SAMESITE = "Lax"

# En producción con HTTPS, activar cookies seguras
# Por ahora, desactivado para EB sin SSL
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.ngrok.io",           # URLs antiguas de ngrok
    "https://*.ngrok-free.app",     # URLs nuevas de ngrok (desde 2023)
    "https://*.ngrok.app",
    "https://*.ngrok-free.dev",     # Variante adicional
    "https://*.railway.app",        # Railway
    "https://*.up.railway.app",     # Railway (variante)
    "http://*.elasticbeanstalk.com",   # AWS Elastic Beanstalk (HTTP)
    "https://*.elasticbeanstalk.com",  # AWS Elastic Beanstalk (HTTPS)
]

# Agregar dominio personalizado de Railway si existe
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')


# Logging
# Configuración de logging condicional
if DEBUG:
    # En desarrollo: usar archivos de log
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
                "style": "{",
            },
            "json": {
                "format": '{"level": "%(levelname)s", "time": "%(asctime)s", "module": "%(module)s", "message": "%(message)s"}',
            },
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": os.path.join(LOGS_DIR, "audit.log"),
                "formatter": "verbose",
            },
            "security_file": {
                "level": "WARNING",
                "class": "logging.FileHandler",
                "filename": os.path.join(LOGS_DIR, "security.log"),
                "formatter": "json",
            },
            "audit_file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": os.path.join(LOGS_DIR, "audit.log"),
                "formatter": "json",
            },
            "console": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["file", "console"],
                "level": "INFO",
                "propagate": True,
            },
            "security": {
                "handlers": ["security_file"],
                "level": "WARNING",
                "propagate": False,
            },
            "audit": {
                "handlers": ["audit_file"],
                "level": "INFO",
                "propagate": False,
            },
            "actas.email_service": {
                "handlers": ["file"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
else:
    # En producción (Railway): usar solo consola
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": True,
            },
            "security": {
                "handlers": ["console"],
                "level": "WARNING",
                "propagate": False,
            },
            "audit": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "actas.email_service": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }


# URLs de login/logout
LOGIN_URL = "/accounts/login/"  # Si alguien no está logueado, se manda a /login/
LOGIN_REDIRECT_URL = "/"  # Después de login va al dashboard (raíz)
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Después de logout vuelve al login

# ==============================================================================
# CONFIGURACIÓN DE AUTENTICACIÓN Y SEGURIDAD ADICIONAL
# ==============================================================================

PASSWORD_RESET_TIMEOUT = 3600
PASSWORD_RESET_COMPLETE_URL = "/accounts/login/"

# Token de API - expiración en horas (24 horas por defecto)
TOKEN_EXPIRATION_HOURS = config('TOKEN_EXPIRATION_HOURS', default=24, cast=int)


DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-responder@sena.edu.co")

SITE_DOMAIN = config("SITE_DOMAIN", default="127.0.0.1:8000")

# ========================================
# CONFIGURACIÓN GROQ 
# ========================================
GROQ_API_KEY = config("GROQ_API_KEY", default="")
GROQ_MODEL = config("GROQ_MODEL", default="llama3-70b-8192")
GROQ_TIMEOUT = config("GROQ_TIMEOUT", default=30, cast=int)

# Habilitar IA
IA_ENABLED = config("IA_ENABLED", default=True, cast=bool)

# Límites opcionales
IA_DAILY_LIMIT_PER_USER = config("IA_DAILY_LIMIT_PER_USER", default=50, cast=int)

# ==============================================
# CORS Configuration (para app móvil)
# ==============================================
# En producción, usar CORS_ALLOWED_ORIGINS con dominios específicos
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000'
).split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
    'Content-Type',
    'Content-Length',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuración de Email (usando variables de entorno por seguridad)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')